USE gestion_seguros;
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345010, 'Jose',     'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345020, 'Fernando', 'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345030, 'Luis',     'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345040, 'Maria',    'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345050, 'Nicolas',  'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345060, 'Bruno',    'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345080, 'Victoria', 'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345070, 'Leonardo', 'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345090, 'Carlos',   'Comentario; probar inclusion de caracteres especiales');
INSERT INTO clientes (cedula, nombre, comentario) VALUES (12345100, 'Rafael',   'Comentario; probar inclusion de caracteres especiales');
